CREATE DATABASE crud;
USE crud;
CREATE TABLE usuarios(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
nome VARCHAR(80) NOT NULL,
sobrenome VARCHAR(80) NOT NULL,
usuario VARCHAR(60) NOT NULL,
email VARCHAR(120) NOT NULL,
senha TEXT NOT NULL,
sexo CHAR(1) NOT NULL,
PRIMARY KEY(id)
)ENGINE = INNODB;